### ISSUE TITLE
Potential docker-compose.yml optimization

### ISSUE THREAD

**Issue by AdFisch** [n8n-io/n8n-docker-caddy#6]
Hi everyone,

I have to warn you that I am new to Docker and using n8n inside containers. Thus, I just read a lot of documentation which left me with a few questions concerning the docker-compose.yml file and potential optimizations:

I understand there are two types of volumes:

1) "Config volumes" which are used to pass configurations from the host to the containers (namely caddy_config and Caddyfile)
2) "Persistant volumes" which are created to allow n8n and Caddy to store data persistantly (namely caddy_data, local_files and .n8n)

So my first 2 questions are:

* Since config volumes only need to be read by the hosts, wouldn't it be "safer" to make them read-only using ":ro"?
* And for persistant volumes, wouldn't it be "safer" to use Docker volumes instead of bind mounts (https://docs.docker.com/storage/volumes/)?

My last question is concerning the 2 named volumes defined globally at the end of the file (external "caddy_data" and "caddy_config"). If I understand things right, the named volumes are not used by any services. So:

* Can the named volumes be left out?

To sum things up, is the following docker-compose.yml file an optimized version of the current one (assuming caddy_data has not been initiated by Docker before)?

```
version: "3.7"

services:

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - ${DATA_FOLDER}/caddy_config:/config:ro
      - ${DATA_FOLDER}/caddy_config/Caddyfile:/etc/caddy/Caddyfile:ro

  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - local_files:/files
      - n8n:/home/node/.n8n

volumes:
  caddy_data:
  local_files:
  n8n:
```

As I said, I am new to the topic - so sorry, if there are any obvious mistakes. Thanks for your help/consideration! :-)
